name: "food_sharing_map"
version: "1.0.0"
config-version: 2

profile: "food_sharing_map"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  food_sharing_map:
    staging:
      +schema: silver
      +materialized: table
    marts:
      +schema: gold
      +materialized: table
